version: '3.8'
services:
  metabase:
    image: 'metabase/metabase'
    ports:
      - 3000:3000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  postgres-db-volume: